name: "Subdomain finding using subfinder"
author: "v1dhun"
description: "Subfinder is a subdomain discovery tool developed by ProjectDiscovery.io."
branding:
  icon: "alert-circle"
  color: "blue"

inputs:
  urls:
    description: "List of domains to run subfinder"
    required: true
  telegram-chat-id:
    description: "Telegram chat id to send notifications"
    required: false
  telegram-token:
    description: "Telegram bot token to send notifications"
    required: false
  check-alive:
    description: "To check host is alive or not using httpx"
    required: false
    default: "false"
  config-list:
    description: "Configuration file for API Keys, etc"
    required: false


runs:
  using: "composite"
  steps:
    - run: | 
       GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@sarif-integration
      shell: bash
    - run: nuclei -list ${{ inputs.urls }} --silent -sf lol
      shell: bash
