name: Nuclei - DAST

inputs:
  target:
    description: "Target to scan for Nuclei"
    required: false
  urls:
    description: "List of domains to run Nuclei"
    required: false
  config:
    description: "Nuclei config file"
    required: false
  output:
    description: "output file"
    required: false

runs:
  using: "composite"
  steps:
    - run: | 
       GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@sarif-integration
       nuclei -silent -ut
       nuclei -silent -target ${{ inputs.target }} --silent -sf nuclei.sarif -t ~/nuclei-templates/ -o ${{ inputs.output }}
      shell: bash
