name: Nuclei - DAST

on:
  workflow_dispatch:

jobs:
  worker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: /home/runner/go/bin/nuclei
          key: ${{ runner.os }}-${{ hashFiles('/home/runner/go/bin/nuclei') }}

      - uses: projectdiscovery/nuclei-action@main
        with:
          urls: "urls.txt"
          templates: "."
          output: "nuclei.log"

      - uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log
