name: DEMO 1

on:
  workflow_dispatch:

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ehsandeep/nuclei-actionn@main
        with:
          target: https://example.com

