name: Nuclei - DAST

on:
  workflow_dispatch:

jobs:
  worker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: /home/runner/go/bin/nuclei
          key: ${{ runner.os }}-${{ hashFiles('/home/runner/go/bin/nuclei') }}

      - uses: ehsandeep/nn-action@main
        with:
          target: "https://example.com"
          sarif-export: "nuclei.sarif"

      - name: Update GitHub Security alert Dashboard
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: nuclei.sarif
