name: Nuclei Action

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Setting up ProjectDiscovery tools
        env:
          GO111MODULE: on
        run: |
          go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@2c0cea1a3f3c60d73731fc9f910eabb60cb714d8
        shell: bash

      - name: Downloading Nuclei Templates
        run: |
          nuclei -update-templates -silent
        shell: bash

      - name: Running Nuclei
        run: |
          nuclei -u test -silent -t test/file.yaml -sf nuclei.sarif
        shell: bash

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: nuclei.sarif
