name: DEMO 0

on:
  workflow_dispatch:

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: fguisso/nuclei-action@flags
        with:
          target: https://example.com
          output: nuclei.log

      - uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log
