name: "Subdomain finding using subfinder"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * FRI"

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: ehsandeep/nuclei-action@main
        with:
          urls: urls.txt
          json: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: nuclei.sarif
