name: "Subdomain finding using subfinder"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * FRI"

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ehsandeep/nuclei-action@main
        with:
          domains-list: domains.txt
